---
name: github actions syntax sandbox

on:
  push:
    branches:
      - master
      - private-runner

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  one-line-run:
    name: line continuation check
    runs-on: ubuntu-18.04
    steps:
      - name: package purging
        run: dpkg -l apt purge ghc-8.8.4 ghc-8.10.3 ghc-8.6.5 \
          azure-cli google-cloud-sdk \
          sudo apt purge google-chrome-stable firefox
